-- 코드를 입력하세요
SELECT F.FLAVOR FROM FIRST_HALF AS F JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL FROM JULY GROUP BY FLAVOR) AS J ON F.FLAVOR = J.FLAVOR ORDER BY (F.TOTAL_ORDER + J.TOTAL) DESC LIMIT 3;